apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argoapps-selfsigned-cert
spec:
  isCA: true
  commonName: argoapps.corp.internal
  secretName: argoapps-cert-tls
  dnsNames:
    - argoapps.corp.internal
  duration: 8760h
  renewBefore: 240h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: argoapps-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
