apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- install.yaml
- issuer.yaml
- certificate.yaml
- ingress.yaml

namespace: argocd

configMapGenerator:
- name: argocd-cmd-params-cm
  behavior: merge
  literals:
  - server.insecure="true"
